project:
  type: website
  output-dir: docs
  execute-dir: project
  render:
    - index.qmd
    - observations.qmd
    - predictors.qmd
    - covariates.qmd
    - about.qmd
execute: 
  cache: true

website:
  title: "Species distribution modeling with R"
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - href: observations.qmd
        text: Observations
      - href: predictors.qmd
        text: Predictors
      - href: covariates.qmd
        text: Extracting covariates
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    number-sections: true

editor: source

